-- Add missing ItemType enum values
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DONGHUA';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'MANHWA';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'MANHUA';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'HENTAI';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'AENI';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'ANIMATION';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'WEBTOON';
